modLoader = "javafml"
loaderVersion = "${javafml_loader_range}"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "catskinc_remake"
version = "${version}"
displayName = "CatSkinC-Remake"
authors = "Q Team Studio"
description = '''

'''
#logoFile = ""

[[dependencies.catskinc_remake]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_loader_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.catskinc_remake]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.catskinc_remake]]
modId = "architectury"
type = "required"
versionRange = "${architectury_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.catskinc_remake]]
modId = "voicechat"
type = "optional"
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.catskinc_remake]]
modId = "plasmovoice"
type = "optional"
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.catskinc_remake]]
modId = "figura"
type = "optional"
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.catskinc_remake]]
modId = "emotecraft"
type = "optional"
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "catskinc-remake.mixins.json"
